version: '3.8'

services:
  # Banco de dados PostgreSQL
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: escola_infantil
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - escola_network
    restart: unless-stopped

  # API Flask
  api:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/escola_infantil
      SECRET_KEY: escola-infantil-secret-key-2024
      FLASK_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - escola_network
    volumes:
      - .:/app
    restart: unless-stopped

  # Frontend Streamlit
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    environment:
      API_URL: http://api:5000
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - escola_network
    restart: unless-stopped

networks:
  escola_network:
    driver: bridge

volumes:
  postgres_data: